### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by Liskelleo** [yjg30737/pyqt-windows-os-light-dark-theme-window#1]
Hello. Here's some questions for you.
1) I tried to trigger the toggle button, but it couldn't update the theme automatically, which means you need to double-click the title or change the size of the interface to update the theme.
2) The theme cannot be applied to all of the sub-widgets, like QMessageBox, AboutUs, QDialogue, etc. Maybe you could improve the function of this package.
Looking forward to your reply^^

**Comment by yjg30737** [comment]
1. What version of Windows do you use? Windows 11 or 10? I've only tested this in Windows 11.. at least that's what i remember. In Windows 11, theme is switched immediately. 

2. This is very basic example of it so i didn't do that.. If i applied the style change to all of the applications' windows, i have to handle nativeEvent at QApplication level or some sort. I'm not sure i can do that but i will try later.

I give you this link in case you are in a hurry

https://doc.qt.io/qt-6/qcoreapplication.html#installNativeEventFilter

I didn't read this carefully enough, but i think this is the key to solve the problem

**Comment by Liskelleo** [comment]
1) I use Windows 10 to test your code, so it might occur the situation of incompatibility.
2) I'll have a look and give it a try.

**Comment by yjg30737** [comment]
I will test it out on Windows 10 in my virtual machine, and if it is possible, i will solve that problem as well.

**Comment by Liskelleo** [comment]
OK then, any progress if you make you can tell me.

**Comment by yjg30737** [comment]
Well.. I'm exhausted.

I made a progress, but that was quite a journey to me. 

First of all i acutally found out that `DWMWA_USE_IMMERSIVE_DARK_MODE` which i used for switching theme is supported since Windows 11.

This still works for some reasons in Windows 10 as well, but as you said if it has not been resized it doesn't change the theme by itself.

So this is how i did that:

```python
if self.isMaximized() or self.isFullScreen() or self.maximumWidth() == self.width():
            if self.isMaximized():
                self.showNormal()
                self.showMaximized()
            elif self.isFullScreen():
                self.showNormal()
                self.showFullScreen()
            elif self.maximumWidth() == self.width():
                self.resize(self.width()-1, self.height())
                self.resize(self.width()+1, self.height())
        else:
            self.resize(self.width()+1, self.height())
            self.resize(self.width()-1, self.height())
```

It's kinda shame that i wrote that kind of codes but there's nothing i can do 😥

As far as i know, i've never seen a single software which is made out of PyQt using win32 feature(customized title bar doesn't count), able to switch theme in real-time.

But at least it works now, in a very, very crude way..

**Comment by Liskelleo** [comment]
Hmm, this is a solution of compromise, but so far so good. Thank you for working on this, and I'm really appreciate for your patient reply^^
